### ISSUE TITLE
Code failing to compile

### ISSUE THREAD

**Issue by tushu1232** [SHuang-Broad/bwamem-index-image#1]
git clone https://github.com/lh3/bwa --branch Apache2  && cd bwa && git checkout ec85a563e64710e7fc8c8c0b373d80570e245bd1
Initialized empty Git repository in /tpathare/bwamem-index-image/bwa/.git/
remote: Counting objects: 4071, done.
remote: Total 4071 (delta 0), reused 0 (delta 0), pack-reused 4071
Receiving objects: 100% (4071/4071), 1.57 MiB | 534 KiB/s, done.
Resolving deltas: 100% (2905/2905), done.
Note: checking out 'ec85a563e64710e7fc8c8c0b373d80570e245bd1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at ec85a56... Merge pull request #100 from tedsharpe/add_formatting_hook
make CFLAGS="-Wall -Wno-unused-function -O2" -C bwa libbwa.a
make[1]: Entering directory `/tpathare/bwamem-index-image/bwa'
gcc -c -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  utils.c -o utils.o
gcc -c -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  kthread.c -o kthread.o
gcc -c -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  kstring.c -o kstring.o
gcc -c -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  ksw.c -o ksw.o
gcc -c -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwt.c -o bwt.o
gcc -c -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bntseq.c -o bntseq.o
gcc -c -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwa.c -o bwa.o
gcc -c -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwamem.c -o bwamem.o
gcc -c -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwamem_pair.c -o bwamem_pair.o
gcc -c -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwamem_extra.c -o bwamem_extra.o
gcc -c -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  malloc_wrap.c -o malloc_wrap.o
ar -csru libbwa.a utils.o kthread.o kstring.o ksw.o bwt.o bntseq.o bwa.o bwamem.o bwamem_pair.o bwamem_extra.o malloc_wrap.o
make[1]: Leaving directory `/tpathare/bwamem-index-image/bwa'
gcc -Wall -Wno-unused-function -O2 bwa/libbwa.a image.c main.c -o create_bwamem_index_image -L. -lm -lz -lpthread
main.c: In function ‘main’:
main.c:9: warning: control reaches end of non-void function
/tmp/cclHH84I.o: In function `createIndexFile':
image.c:(.text+0x19): undefined reference to `bwa_idx_load'
image.c:(.text+0x24): undefined reference to `bwa_idx2mem'
image.c:(.text+0x13c): undefined reference to `bwa_idx_destroy'
collect2: ld returned 1 exit status
make: *** [create_bwamem_index_image] Error 1

**Comment by SHuang-Broad** [comment]
@tushu1232 , can you please pull again and checkout the branch `fix_linker-err` and 
`make` again?
It should work now. If it does, please let me know and I'll merge the change into master.

Thanks.

**Comment by SHuang-Broad** [comment]
@tushu1232 ping

**Comment by SHuang-Broad** [comment]
closed by #2
